spring:
  application:
    name: CourseSearch
  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
      index:
        create-index: false

